In [1]:
#A warehouse manages inventory for 5 products stored across 4 locations. The stock levels are recorded in a 2D NumPy array, where rows represent products and columns represent locations:
import numpy as np
#initilize an array
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])


In [2]:
#1 dimention of the array
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr.size

20

In [3]:
#2 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])

arr.dtype

dtype('int32')

In [4]:
#3 
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr.size

20

In [5]:
#4 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr.itemsize

4

In [7]:
#5 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr.sum()

3810

In [12]:
#6 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[2]-= 10
print(arr)

[[100 200 150 300]
 [ 50  60  40  80]
 [290 390 340 490]
 [200 250 220 270]
 [ 80  90  70 100]]


In [15]:
#7 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr+=20
print(arr)

[[120 220 170 320]
 [ 70  80  60 100]
 [320 420 370 520]
 [220 270 240 290]
 [100 110  90 120]]


In [17]:
#8 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[0:6,1]*=2
print(arr)


[[100 400 150 300]
 [ 50 120  40  80]
 [300 800 350 500]
 [200 500 220 270]
 [ 80 180  70 100]]


In [3]:
#9 
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[0:6,1]*=2
print(arr)

[[100 400 150 300]
 [ 50 120  40  80]
 [300 800 350 500]
 [200 500 220 270]
 [ 80 180  70 100]]


In [4]:
#10.
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
np.sum(arr,axis=0)

array([ 730, 1000,  830, 1250])

In [5]:
#11
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
np.max(arr,axis=0)

array([300, 400, 350, 500])

In [6]:
#12
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
np.sum(arr,axis=1)

array([ 750,  230, 1550,  940,  340])

In [7]:
#13
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
np.min(arr,axis=1)

array([100,  40, 300, 200,  70])

In [9]:
#14
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
np.mean(arr,axis=1)

array([187.5,  57.5, 387.5, 235. ,  85. ])

In [11]:
#15
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[1]

array([50, 60, 40, 80])

In [12]:
#16
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[:,3]

array([300,  80, 500, 270, 100])

In [14]:
#17
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[0:3,0:2]

array([[100, 200],
       [ 50,  60],
       [300, 400]])

In [19]:
#18
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[3:6,2:4]

array([[220, 270],
       [ 70, 100]])

In [20]:
#19
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[4:6,3:4]

array([[100]])

In [21]:
#20
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
stock_level=arr[[0,3],[0,2]]
stock_level

array([100,220])

In [22]:
#21
import numpy as np
arr=np.array([
    [100, 200, 150, 300],  # Product 1
    [50, 60, 40, 80],      # Product 2
    [300, 400, 350, 500],  # Product 3
    [200, 250, 220, 270],  # Product 4
    [80, 90, 70, 100]      # Product 5
])
arr[1, 3] = 100
print(arr)

[[100 200 150 300]
 [ 50  60  40 100]
 [300 400 350 500]
 [200 250 220 270]
 [ 80  90  70 100]]
